name: Star Helper

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  star-helper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/star-helper@v1.0.0
        with:
          token: ${{ secrets.STAR_TOKEN }}
          actions: 'unstar, star'
          repo: 'ant-design/ant-design'
